name: Submit Gmail
description: Provide your personal Gmail address.
title: "[Gmail]: "
labels: ["email"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide your Gmail address below. **Gmail only (personal Gmail, NOT a school Gmail).**
  - type: input
    id: gmail_address
    attributes:
      label: Personal Gmail Address
      description: "Example: If your email is John21@gmail.com, then only input that."
      placeholder: "John21@gmail.com"
    validations:
      required: true
